### ISSUE TITLE
Update metric names in README.md

### ISSUE THREAD

**Issue by jaroslavcervenka** [alexvaluyskiy/prometheus-net-contrib#25]
Please update ŔEADME.md file. In release 0.9.2 a lot of metrics of SQL client have been removed (e.g. sqlclient_sent_buffers). I needed to investigate missing metrics in our dashboard. Thanks

**Comment by alexvaluyskiy** [comment]
I've removed those metrics, because they were too unstable.
But I could get them back in the future
